### ISSUE TITLE
cannot access org.codehaus.plexus.logging.AbstractLogEnabled

### ISSUE THREAD

**Issue by hackerwin7** [codehaus-plexus/plexus-archiver#54]
dependency info:
```
<dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-archiver</artifactId>
            <version>3.4</version>
</dependency>
```

get the building error:
```
Error:(116, 19) java: cannot access org.codehaus.plexus.logging.AbstractLogEnabled
  class file for org.codehaus.plexus.logging.AbstractLogEnabled not found
```

I found the org.codehaus.plexus.logging.AbstractLogEnabled in the plexus-container-default, so I add this dependency:
```
<dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-container-default</artifactId>
            <version>1.7.1</version>
</dependency>
```

then build successfully, when I run the project, get the exception:
```
Exception in thread "main" java.lang.NullPointerException
	at org.codehaus.plexus.archiver.tar.TarUnArchiver.execute(TarUnArchiver.java:102)
	at org.codehaus.plexus.archiver.tar.TarUnArchiver.execute(TarUnArchiver.java:87)
	at org.codehaus.plexus.archiver.AbstractUnArchiver.extract(AbstractUnArchiver.java:133)
```

the TarUnArchiver.java:102 is this line:
```
getLogger().info( "Expanding: " + sourceFile + " into " + destDirectory );
```

getLogger is null, the getLogger is AbstractLogEnabled.getLogger()

must call enableLogging() before call extract() ????

**Comment by hackerwin7** [comment]
Okay,
Got it, thanks!
