### ISSUE TITLE
Slow build of BZ2 archives

### ISSUE THREAD

**Issue by rkrell** [codehaus-plexus/plexus-archiver#9]
After running into issue #8 I updated to assembly plugin 2.5.5 and in fact the build run faster some time. Now I'm stuck again with a very slow creation of tar.bz2 archives. Not so slow but many times slower than native tools, about 13 minutes to build an archive of a packed size of 290 MB.
It seems like this happens just sometimes.

Except of the increased version of the assembly plugin the same parameters like in issue #8.

Maybe this is expected, of course feel free if you think there cannot be done anything.

Stacktrace:
```
2015-07-10 14:14:02
Full thread dump Java HotSpot(TM) 64-Bit Server VM (20.45-b01 mixed mode):

"Thread-47725" daemon prio=10 tid=0x00007fab77c3a800 nid=0x2f1c waiting on condition [0x00007fab29c1c000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007a0875378> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:196)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2025)
        at java.util.concurrent.DelayQueue.take(DelayQueue.java:164)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:609)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:602)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
        at java.lang.Thread.run(Thread.java:662)

"CachedJobThread-1" daemon prio=10 tid=0x00007fab00053800 nid=0x58f6 in Object.wait() [0x00007fab2a392000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000794443600> (a gk.common.util.ThreadCache$JobThread)
        at java.lang.Object.wait(Object.java:485)
        at gk.common.util.ThreadCache$JobThread.run(ThreadCache.java:176)
        - locked <0x0000000794443600> (a gk.common.util.ThreadCache$JobThread)

"CachedJobThread-0" daemon prio=10 tid=0x00007faaee453000 nid=0x20f6 in Object.wait() [0x00007fab2b3f2000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000078f55e7d8> (a gk.common.util.PlanTable)
        at gk.common.util.LoopThread$LoopJob.run(LoopThread.java:109)
        - locked <0x000000078f55e7d8> (a gk.common.util.PlanTable)
        at gk.common.util.ThreadCache$JobThread.run(ThreadCache.java:171)

"CachedJobThread-1" daemon prio=10 tid=0x00007fab20008000 nid=0x4132 in Object.wait() [0x00007fab2acf0000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000007857c5ec0> (a gk.common.util.ThreadCache$JobThread)
        at java.lang.Object.wait(Object.java:485)
        at gk.common.util.ThreadCache$JobThread.run(ThreadCache.java:190)
        - locked <0x00000007857c5ec0> (a gk.common.util.ThreadCache$JobThread)

"resolver-5" daemon prio=10 tid=0x00007fab760f5000 nid=0x3f3f waiting on condition [0x00007fab2b6f5000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007817d9bc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
        at java.lang.Thread.run(Thread.java:662)

"resolver-4" daemon prio=10 tid=0x00007fab760cf800 nid=0x3f3e waiting on condition [0x00007fab2b7f6000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007817d9bc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
        at java.lang.Thread.run(Thread.java:662)

"resolver-3" daemon prio=10 tid=0x00007fab760cf000 nid=0x3f3d waiting on condition [0x00007fab2bfc0000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007817d9bc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
        at java.lang.Thread.run(Thread.java:662)

"resolver-2" daemon prio=10 tid=0x00007fab760b7800 nid=0x3f3c waiting on condition [0x00007fab2ba74000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007817d9bc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
        at java.lang.Thread.run(Thread.java:662)

"resolver-1" daemon prio=10 tid=0x00007fab760da000 nid=0x3f3b waiting on condition [0x00007fab2bb75000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000007817d9bc8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
        at java.lang.Thread.run(Thread.java:662)

"CachedJobThread-0" daemon prio=10 tid=0x00007fab75893800 nid=0x3ee8 in Object.wait() [0x00007fab2bebf000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000007828a8ab0> (a gk.common.util.PlanTable)
        at gk.common.util.LoopThread$LoopJob.run(LoopThread.java:109)
        - locked <0x00000007828a8ab0> (a gk.common.util.PlanTable)
        at gk.common.util.ThreadCache$JobThread.run(ThreadCache.java:181)

"Timer-0" daemon prio=10 tid=0x00007fab75001800 nid=0x3ee2 in Object.wait() [0x00007fab70101000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x0000000782890420> (a java.util.TaskQueue)
        at java.util.TimerThread.mainLoop(Timer.java:509)
        - locked <0x0000000782890420> (a java.util.TaskQueue)
        at java.util.TimerThread.run(Timer.java:462)

"Thread-1" daemon prio=10 tid=0x00007fab74b3f800 nid=0x3ee1 waiting on condition [0x00007fab716a5000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000078152c220> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:196)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2025)
        at java.util.concurrent.DelayQueue.take(DelayQueue.java:164)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:609)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:602)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
        at java.lang.Thread.run(Thread.java:662)

"Low Memory Detector" daemon prio=10 tid=0x00007fab74098800 nid=0x3ede runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=10 tid=0x00007fab74096800 nid=0x3edd waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=10 tid=0x00007fab74093800 nid=0x3edc waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" daemon prio=10 tid=0x00007fab74091800 nid=0x3edb waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=10 tid=0x00007fab74074800 nid=0x3eda in Object.wait() [0x00007fab722d2000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000078236cfa0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:118)
        - locked <0x000000078236cfa0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:134)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:171)

"Reference Handler" daemon prio=10 tid=0x00007fab74072800 nid=0x3ed9 in Object.wait() [0x00007fab723d3000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000078236cf60> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:485)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:116)
        - locked <0x000000078236cf60> (a java.lang.ref.Reference$Lock)

"main" prio=10 tid=0x00007fab74006000 nid=0x3ecf runnable [0x00007fab7bc43000]
   java.lang.Thread.State: RUNNABLE
        at org.codehaus.plexus.archiver.commonscompress.compressors.bzip2.BZip2CompressorOutputStream.generateMTFValues(BZip2CompressorOutputStream.java:1209)
        at org.codehaus.plexus.archiver.commonscompress.compressors.bzip2.BZip2CompressorOutputStream.moveToFrontCodeAndSend(BZip2CompressorOutputStream.java:1153)
        at org.codehaus.plexus.archiver.commonscompress.compressors.bzip2.BZip2CompressorOutputStream.endBlock(BZip2CompressorOutputStream.java:585)
        at org.codehaus.plexus.archiver.commonscompress.compressors.bzip2.BZip2CompressorOutputStream.writeRun(BZip2CompressorOutputStream.java:463)
        at org.codehaus.plexus.archiver.commonscompress.compressors.bzip2.BZip2CompressorOutputStream.write0(BZip2CompressorOutputStream.java:651)
        at org.codehaus.plexus.archiver.commonscompress.compressors.bzip2.BZip2CompressorOutputStream.write(BZip2CompressorOutputStream.java:632)
        at org.codehaus.plexus.archiver.commonscompress.utils.CountingOutputStream.write(CountingOutputStream.java:48)
        at org.codehaus.plexus.archiver.commonscompress.archivers.tar.TarArchiveOutputStream.writeRecord(TarArchiveOutputStream.java:570)
        at org.codehaus.plexus.archiver.commonscompress.archivers.tar.TarArchiveOutputStream.write(TarArchiveOutputStream.java:434)
        at org.codehaus.plexus.archiver.util.Streams.copyFullyDontCloseOutput(Streams.java:118)
        at org.codehaus.plexus.archiver.tar.TarArchiver.tarFile(TarArchiver.java:336)
        at org.codehaus.plexus.archiver.tar.TarArchiver.execute(TarArchiver.java:189)
        at org.codehaus.plexus.archiver.AbstractArchiver.createArchive(AbstractArchiver.java:1039)
        at org.apache.maven.plugin.assembly.archive.archiver.AssemblyProxyArchiver.createArchive(AssemblyProxyArchiver.java:437)
        at org.apache.maven.plugin.assembly.archive.DefaultAssemblyArchiver.createArchive(DefaultAssemblyArchiver.java:181)
        at org.apache.maven.plugin.assembly.mojos.AbstractAssemblyMojo.execute(AbstractAssemblyMojo.java:484)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

"VM Thread" prio=10 tid=0x00007fab7406b800 nid=0x3ed8 runnable 

"GC task thread#0 (ParallelGC)" prio=10 tid=0x00007fab74019000 nid=0x3ed0 runnable 

"GC task thread#1 (ParallelGC)" prio=10 tid=0x00007fab7401b000 nid=0x3ed1 runnable 

"GC task thread#2 (ParallelGC)" prio=10 tid=0x00007fab7401d000 nid=0x3ed2 runnable 

"GC task thread#3 (ParallelGC)" prio=10 tid=0x00007fab7401e800 nid=0x3ed3 runnable 

"GC task thread#4 (ParallelGC)" prio=10 tid=0x00007fab74020800 nid=0x3ed4 runnable 

"GC task thread#5 (ParallelGC)" prio=10 tid=0x00007fab74022800 nid=0x3ed5 runnable 

"GC task thread#6 (ParallelGC)" prio=10 tid=0x00007fab74024000 nid=0x3ed6 runnable 

"GC task thread#7 (ParallelGC)" prio=10 tid=0x00007fab74026000 nid=0x3ed7 runnable 

"VM Periodic Task Thread" prio=10 tid=0x00007fab740ab800 nid=0x3edf waiting on condition 

JNI global references: 1472

Heap
 PSYoungGen      total 203456K, used 81247K [0x00000007f0000000, 0x0000000800000000, 0x0000000800000000)
  eden space 140032K, 52% used [0x00000007f0000000,0x00000007f4749f08,0x00000007f88c0000)
  from space 63424K, 13% used [0x00000007fc210000,0x00000007fca1df50,0x0000000800000000)
  to   space 58688K, 0% used [0x00000007f88c0000,0x00000007f88c0000,0x00000007fc210000)
 PSOldGen        total 969792K, used 536351K [0x0000000780000000, 0x00000007bb310000, 0x00000007f0000000)
  object space 969792K, 55% used [0x0000000780000000,0x00000007a0bc7df8,0x00000007bb310000)
 PSPermGen       total 524288K, used 328778K [0x0000000740000000, 0x0000000760000000, 0x0000000780000000)
  object space 524288K, 62% used [0x0000000740000000,0x00000007541129d0,0x0000000760000000)
```

**Comment by krosenvold** [comment]
Now this is where things get interesting ! Initially you thought 2.5.5 was fast, but then it somehow got slower ? Are you running on linux ? If so, does running "sudo apt-get install randomsound" help ? (or yum or whatever package manager you're using...)

**Comment by rkrell** [comment]
I've got a notion that you rather want to close this :-)
Feel free to do so, I just wanted to notice you where the current implementation takes the most time. Nevertheless, packaging tar.bz2 is many times faster using the assembly plugin 2.5.5 instead of 2.4, this has been helpful anyway.
:+1:

**Comment by krosenvold** [comment]
You are misunderstanding me totally :) I actually enjoy looking for performance issues quite a lot. So even before I realized you were runnning on an old version of the assembly plugin, I actually found a 20% overall performance improvement in plexus-archiver that applies when creating archives with many small files (you can have that for free by updating to plexus-io 2.6.1 inside the "dependencies" section of your assembly plugin if this issue applies to you...)

But in general, when people are running old versions of software they are generally on their own; committers prefer to work on the recent code base and not solve problems that have already been solved :) For some very stable pieces of code it might not matter if it's 2 or even 5 years old, but most java code is not that mature. And in ploexus-archiver we switched the implementations to commons-compress about 9 months ago, so anything older than that is dinosaur-material.

Now you're not really giving me much to work by, but you /seem/ to indicate that your build ran really fast but has for some reason slowed down. There are actually a few well-defined causes of behaviour like this, and one of them is running out of os-level entropy on linux ( I am not kidding you, this is serious stuff!) . Another is fragmentation behaviour of SSD's, ensure that your SSD supports TRIM and that the OS-level "discard" setting has been activated on the device in /etc/fstab (assuming it's a SSD). I am somewhat unsure if we should be capable of *beating* OS-level bz2, but we should basically come within a well-defined proportion. For zip I actually assume we beat unix "zip" in recent versions since we're multithreaded.

**Comment by rkrell** [comment]
Sorry for that and thanks for the comprehensive hint :-)
I really thought the thing with the randomsound were a joke :-)

I will probably have to build this package by myself, there is no package available called randomsound for my OpenSUSE Tumbleweed (factory).

I will watch also the performance with an updated plexus-io.

In fact the piece of hardware I reported this against uses a SSD disk, formatted with two ext4 partitions:
- /dev/sda2 on / type ext4 (rw,relatime,data=ordered)
- /dev/sda3 on /home type ext4 (rw,relatime,data=ordered)
It is a HP ZBook 15.

There is no need to beat the native apps in performance, but I was surprised about the increasement from a few hours to less than a minute for the first time.

I'll let you know if there will be some interesting results.

**Comment by rkrell** [comment]
Update: On the original system I got again a build time around one minute of the mentioned BZ2 with a size of 290 MB. This is again near the performance of the assembly plugin 2.5.5 with the original dependencies like the native tools. Thus this is really an OS issue, as you say. Good work, thank you so far.
If there will be any drawbacks on other systems I will tell you here. Otherwise there seems not to be a real issue.

**Comment by krosenvold** [comment]
Running out of entropy is a serious business on linux, and Java in general is greedy when it comes to entropy. There are a number of other packages you can use too, I just have good experiences with randomsound, which collects entropy from the sound card. I also note that you do not seem to have the "discard" option in your fstab options, which can be a real drag. So you have two things to fix :)

**Comment by rkrell** [comment]
Regarding the entropy pool on OpenSUSE which is the OS I've been reporting against:
There is an active daemon haveged - "Entropy Daemon based on the HAVEGE algorithm", version 1.9.1. This should probably handle it on this distribution.

I will check and add the "discard" option if possible. Thanks for the hint.

**Comment by krosenvold** [comment]
I would actively monitor the state of entropy doing something like this post;
https://major.io/2007/07/01/check-available-entropy-in-linux/

Last time I checked (arguably a few years ago) HAVEGE was not too good on a machine with SSD and no rotational media. But as long as your entropy stays solidly above a few hundred you're safe.
